* Offsets


These offsets were calculated by evaluating the hex diff in ~perfectdark.c~

| MouseInector pointer name | MouseInjector offset |
| PD_deathflag              |                 0xd8 |
| PD_stanceflag             |                 0xac |
| PD_camx                   |                0x144 |
| PD_camy                   |                0x154 |
| PD_fov                    |               0x1848 |
| PD_crosshairx             |               0x1668 |
| PD_crosshairy             |               0x166c |
| PD_grabflag               |                0x1b0 |
| PD_bikeptr                |               0x1a6c |
| PD_thirdperson            |                  0x0 |
| PD_gunrx                  |                0xcd4 |
| PD_gunry                  |                0xcd8 |
| PD_gunlx                  |               0x1478 |
| PD_gunly                  |               0x147c |
| PD_aimingflag             |                0x120 |
| PD_gunrstate              |                0xc3c |
| PD_gunlstate              |               0x13e0 |
| PD_gunrxrecoil            |                0x7f8 |
| PD_gunryrecoil            |                0x7fc |
| PD_gunlxrecoil            |                0xf9c |
| PD_gunlyrecoil            |                0xfa0 |
| PD_currentweapon          |               0x1588 |
| PD_bikebase               |                  0x4 |
| PD_bikeyaw                |                 0x6c |
| PD_bikeroll               |                 0xbc |
| PD_camspybase             |                0x480 |
| PD_camspyflag             |                 0x34 |
| PD_camspyx                |                 0x1c |
| PD_camspyy                |                 0x28 |
| PD_camspyycos             |                 0x2c |
| PD_camspyysin             |                 0x30 |

** script
#+begin_src python :noeval
"""
python snippet used to generate hardcoded offsets
"""
import json

data = {}

# this was pastedf rom MouseInjector/../perfectdark.c
for line in [
  '#define PD_deathflag 0x801BB778 - 0x801BB6A0',
  '#define PD_stanceflag 0x801BB74C - 0x801BB6A0',
  '#define PD_camx 0x801BB7E4 - 0x801BB6A0',
  '#define PD_camy 0x801BB7F4 - 0x801BB6A0',
  '#define PD_fov 0x801BCEE8 - 0x801BB6A0',
  '#define PD_crosshairx 0x801BCD08 - 0x801BB6A0',
  '#define PD_crosshairy 0x801BCD0C - 0x801BB6A0',
  '#define PD_grabflag 0x801BB850 - 0x801BB6A0',
  '#define PD_bikeptr 0x801BD10C - 0x801BB6A0',
  '#define PD_thirdperson 0x801BB6A0 - 0x801BB6A0',
  '#define PD_gunrx 0x801BC374 - 0x801BB6A0',
  '#define PD_gunry 0x801BC378 - 0x801BB6A0',
  '#define PD_gunlx 0x801BCB18 - 0x801BB6A0',
  '#define PD_gunly 0x801BCB1C - 0x801BB6A0',
  '#define PD_aimingflag 0x801BB7C0 - 0x801BB6A0',
  '#define PD_gunrstate 0x801BC2DC - 0x801BB6A0',
  '#define PD_gunlstate 0x801BCA80 - 0x801BB6A0',
  '#define PD_gunrxrecoil 0x801BBE98 - 0x801BB6A0',
  '#define PD_gunryrecoil 0x801BBE9C - 0x801BB6A0',
  '#define PD_gunlxrecoil 0x801BC63C - 0x801BB6A0',
  '#define PD_gunlyrecoil 0x801BC640 - 0x801BB6A0',
  '#define PD_currentweapon 0x801BCC28 - 0x801BB6A0',
  '#define PD_bikebase 0x805142C4 - 0x805142C0',
  '#define PD_bikeyaw 0x804B1AB4 - 0x804B1A48',
  '#define PD_bikeroll 0x804B1B04 - 0x804B1A48',
  '#define PD_camspybase 0x801BBB20 - 0x801BB6A0',
  '#define PD_camspyflag 0x801BB6D4 - 0x801BB6A0',
  '#define PD_camspyx 0x80607EEC - 0x80607ED0',
  '#define PD_camspyy 0x80607EF8 - 0x80607ED0',
  '#define PD_camspyycos 0x80607EFC - 0x80607ED0',
  '#define PD_camspyysin 0x80607F00 - 0x80607ED0',
]:
    l = line.split(" ")
    pos = l[-3]
    base = l[-1]
    name = l[-4]
    offset = hex(int(pos, 16) - int(base, 16))
    d = {
        name: offset
        }
    data.update(d)
    # if base not in data:
    #     data[base] = [d]
    # else:
    #     data[base].append(d)
# print(f"{json.dumps(data, indent=2)}")
for k,v in data.items():
    print(f"#define {k} {v}")
return data
#+end_src
*  Mouse Injector
The MouseInjectorPlugin is a Windows Dll purpose-built for, and bundled with, the 1964GEPD emulator for Goldeneye / Perfect Dark to enable aiming via mouse and QOL improvments for keyboard play.


** pointers
Until a PC port is done mods that mess with pointers that the Mouse Injector deals with will be incompatible until:
- for things that require constant interactivity (i.e. aiming), enable direct reads / writes to predictable globals / pointers that be precalculated and passed as as parameter to the Mouse Injector
- overrides and hacks that don't require constant interactivity with the host plugin offloaded to the rom
*** resolvable by ~pd-addr~
**** JOANNADATA(X) :mouseinjector:static:

mouseinjector, static


***** tracing - vanilla PD

#+begin_src shell :noeval
catherine@ganymede ~/src/MouseInjectorPlugin/games $ pd-addr 0x8009A024
address 0x8009a024
symbol g_Vars offset 0x64
#+end_src

#+begin_src c :noeval
struct g_vars {
//...
	/*000064*/ struct player *players[4];
//...
}
#+end_src


**** PD_menu(X) :mouseinjector:static:

observation: this is defined as an extern in data.h

***** tracing - vanilla PD

#+begin_src bash
PD=~/src/perfect-dark pd-addr 0x80070750
#+end_src

#+RESULTS:
| address |           0x80070750 |
| symbol  | g_PlayersWithControl |


#+begin_src c :noeval
// data.h
/**:266**/ extern bool g_PlayersWithControl[];
#+end_src


**** PD_camera :mouseinjector:static:

The MouseInjector docs classify this as a ~camera flag~, but it's actual definition the decomp is ~s32 tickmode~:

- 1 = gameplay
- 2 & 3 = ???
- 4 = multiplayer sweep
- 5 = gameover screen
- 6 = cutscene mode
- 7 = force player to move: extraction's dark room)


***** tracing - vanilla PD
#+begin_src bash
PD=~/src/perfect-dark pd-addr 0x8009A26C
#+end_src

#+RESULTS:
| address | 0x8009a26c |        |       |
| symbol  |     g_Vars | offset | 0x2ac |

#+begin_src c :noeval
struct g_vars {
    //...
    /*0002ac*/ s32 tickmode;
    //...
}
#+end_src



**** PD_introcounter :static:mouseinjector:
Per MouseInector, counter for intro

***** tracing - vanilla PD

#+begin_src bash
ADDRESS=0x800624C4
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address |   0x800624c4 |
| symbol  | g_TitleTimer |



#+RESULTS:
| address |   0x800624c4 |
| symbol  | g_TitleTimer |


**** PD_stageid :mouseinjector:static:
Per the MouseInjector, ~stage id~

***** tracing - vanilla PD

#+begin_src bash
PD=~/src/perfect-dark pd-addr 0x800624E4
#+end_src

#+RESULTS:
| address |       0x800624e4 |
| symbol  | g_TitleNextStage |

#+begin_src c :noeval
//data.h
    extern s32 g_TitleNextStage;
#+end_src


**** PD_weapontable :mouseinjector:static:
0x8006FF1C
Per the MouseInjector, weapon pointer table, used to change view model positions
***** tracing - vanilla PD
#+begin_src bash
ADDRESS=0x8006FF1C
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x8006ff1c |        |     |
| symbol  |  g_Weapons | offset | 0x4 |

**** PD_mppause :mouseinjector:static:
Per the MouseInjector, used to check if multiplayer match is paused

***** tracing - vanilla PD

#+begin_src bash
PD=~/src/perfect-dark pd-addr 0x800ACBA6
#+end_src

#+RESULTS:
| address | 0x800acba6 |        |      |
| symbol  |  g_MpSetup | offset | 0x1e |



#+RESULTS:
| address | 0x800acba6 |        |      |
| symbol  |  g_MpSetup | offset | 0x1e |


*** not resolvable by ~pd-addr~

These all get odd offsets that don't seem to make sense. Not sure if this is a limitation of the PDTOOLs that generated the memory maps, the build process, or something else. Thankfully none of their handlers in the =MouseInector= look too horible to integreate into a pd rom.

**** PD_defaultratio :trainingdata:mouseinjector:static:
Per MouseInjector, 16:9 ratio default

Seem to be getting odd trainingdata based offsets

***** tracing - vanilla PD

#+begin_src bash
PD=~/src/perfect-dark pd-addr 0x803CD680
#+end_src

#+RESULTS:
| address | 0x803cd680 |        |          |
| symbol  |   g_HtData | offset | 0x3204d0 |

**** PD_defaultfov :trainingdata:mouseinjector:static:
Per MouseInjector, field of view default

Seem to be getting odd trainingdata based offsets
***** tracing - vanilla PD

#+begin_src bash
PD=~/src/perfect-dark pd-addr 0x802EAA5C
#+end_src

#+RESULTS:
| address | 0x802eaa5c |        |          |
| symbol  |   g_HtData | offset | 0x23d8ac |


**** PD_debugtext :trainingdata:mouseinjector:static:
 per the MouseInjector, ~debug text (used to check if PD is running)~


 these results seem to be invalid...they're giving a crazy offset off of a ~trainingdata~ struct

***** tracing - vanilla PD

#+begin_src bash
PD=~/src/perfect-dark pd-addr 0x803C79F0
#+end_src

#+RESULTS:
| address | 0x803c79f0 |        |          |
| symbol  |   g_HtData | offset | 0x31a840 |

**** PD_defaultfovzoom :trainingdata:mouseinjector:static:


Per the MouseInjector, field of view default for zoom

Getting odd trainingdata based offsets

***** tracing - vanilla PD

#+begin_src bash
ADDRESS=0x802EACFC
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x802eacfc |        |          |
| symbol  |   g_HtData | offset | 0x23db4c |

**** PD_defaultzoominspeed :trainingdata:mouseinjector:static:
Per the MouseInjector, default zoom in speed

Getting odd trainingdata based offsets

***** tracing - vanilla PD

#+begin_src bash
ADDRESS=0x802DA8F8
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x802da8f8 |        |          |
| symbol  |   g_HtData | offset | 0x22d748 |



**** PD_defaultzoomoutspeed :trainingdata:mouseinjector:static:

Per the MouseInjector, default zoom out speed

***** tracing - vanilla PD

#+begin_src bash
ADDRESS=0x802DA924
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x802da924 |        |          |
| symbol  |   g_HtData | offset | 0x22d774 |



#+RESULTS:
| address | 0x802da924 |        |          |
| symbol  |   g_HtData | offset | 0x22d774 |

**** PD_controlstyle :static:trainingdata:mouseinjector:
Per the MouseInjector, instruction reads the current controller style

***** tracing - vanilla PD

#+begin_src bash
ADDRESS=0x80372728
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x80372728 |        |          |
| symbol  |   g_HtData | offset | 0x2c5578 |


**** PD_reversepitch :mouseinjector:static:trainingdata:
Per the MouseInjector, instruction reads the current reverse pitch option
***** tracing - vanilla PD

#+begin_src bash
ADDRESS=0x803727A0
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x803727a0 |        |          |
| symbol  |   g_HtData | offset | 0x2c55f0 |

**** PD_pickupyaxisthreshold :mouseinjector:static:trainingdata:
Per the MouseInjector, y axis threshold on picking up weapons

***** tracing - vanilla PD
#+begin_src bash
ADDRESS=0x803CAE78
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x803cae78 |        |          |
| symbol  |   g_HtData | offset | 0x31dcc8 |

**** PD_radialmenutimer :mouseinjector:static:trainingdata:
Per the MouseInjector, time instruction for radial menu to appear (15 ticks)
***** tracing - vanilla PD
#+begin_src bash
ADDRESS=0x802EA2BC
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x802ea2bc |        |          |
| symbol  |   g_HtData | offset | 0x23d10c |

**** PD_radialmenualphainit :trainingdata:static:mouseinjector:
0x803D2CDC
Per the MouseInjctor, initial alpha value for all menus
***** tracing - vanilla PD
#+begin_src bash
ADDRESS=0x803D2CDC
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x803d2cdc |        |          |
| symbol  |   g_HtData | offset | 0x325b2c |

**** PD_blurfix :trainingdata:static:mouseinjector:
0x802DB68C
Per the MouseInjector, nop gap on chr function to store our blur fix
***** tracing - vanilla PD
#+begin_src bash
ADDRESS=0x802DB68C
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x802db68c |        |          |
| symbol  |   g_HtData | offset | 0x22e4dc |
**** PD_hiresoption :trainingdata:static:mouseinjector:
0x80322D9C
Per the MouseInjector, argument used to set hires mode on within options
***** tracing - vanilla PD
#+begin_src bash
ADDRESS=0x80322D9C
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x80322d9c |        |          |
| symbol  |   g_HtData | offset | 0x275bec |
**** PD_camspylookspringup :trainingdata:static:mouseinjector:
0x802F13E8
Per MouseInjector, save instruction for adjusted camspy look spring pitch
***** tracing - vanilla PD
#+begin_src bash
ADDRESS=0x802F13E8
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x802f13e8 |        |          |
| symbol  |   g_HtData | offset | 0x244238 |
**** PD_camspylookspringdown :trainingdata:mouseinjector:static:
0x802F143C
Per MouseInjector, save instruction for adjusted camspy look spring pitch
***** tracing - vanilla PD
#+begin_src bash
ADDRESS=0x802F143C
export PD=~/src/perfect-dark
pd-addr $ADDRESS
#+end_src

#+RESULTS:
| address | 0x802f143c |        |          |
| symbol  |   g_HtData | offset | 0x24428c |